//
//  Constants.swift
//  Odysee
//
//  Created by Akinwale Ariwodola on 14/10/2021.
//

import Foundation

enum Constants {
    static let NotTags: [String] = [
        // MATURE TAGS
        "porn",
        "porno",
        "nsfw",
        "mature",
        "xxx",
        "sex",
        "creampie",
        "blowjob",
        "handjob",
        "vagina",
        "boobs",
        "big boobs",
        "big dick",
        "pussy",
        "cumshot",
        "anal",
        "hard fucking",
        "ass",
        "fuck",
        "hentai",

        // obnoxious, but necessary
        "pron",
        "p0rn",
        "pr0n",
        "s3x",

        // even more, because Apple
        "camporn",
        "fetish",
        "pornographic",
        "pornography",
        // END MATURE TAGS

        // MISC
        "c:unlisted",
    ]

    static let BlockedSearchTerms = [
        // Apple wants everything to be as clean as possible, US edition
        "1488",
        "coon",
        "coonass",
        "coons",
        "chinaman",
        "chinamen",
        "ching chong",
        "dindu",
        "great replacement",
        "nazi",
        "nazis",
        "jew",
        "jews",
        "kike",
        "kikes",
        "negro",
        "negroes",
        "nigga",
        "niggas",
        "nigger",
        "niggers",
        "raghead",
        "ragheads",
        "spic",
        "spick",
        "spics",
        "spicks",
        "spig",
        "spik",
        "spigs",
        "spigotty",
        "spiks",
        "the great replacement",
        "towelhead",
        "towelheads",
    ]

    static let MembersOnly = "c:members-only"

    static let KnownTags = [
        "activism",
        "adventure",
        "agnostic",
        "aliens",
        "altcoins",
        "amazon",
        "anarchy",
        "android",
        "animal",
        "animals",
        "animation",
        "anime",
        "apple",
        "arcade",
        "ark",
        "art",
        "artist",
        "atheism",
        "atheist",
        "audio",
        "australia",
        "auto",
        "automotive",
        "bass",
        "batman",
        "battle royale",
        "beach",
        "beat",
        "beats",
        "beliefs",
        "bible",
        "bitcoin gratis",
        "bitcoin price",
        "bitcoin",
        "black ops 3",
        "black ops",
        "blockchain",
        "bo1",
        "bo2",
        "bo3",
        "bo4",
        "bodybuilding",
        "boss",
        "brasil",
        "btc",
        "building",
        "business",
        "california",
        "call of duty",
        "camping",
        "canon",
        "capcom",
        "car",
        "cars",
        "cartoon",
        "cat",
        "cbs",
        "censorship",
        "chill",
        "chris",
        "christ",
        "christian",
        "christianity",
        "christmas",
        "church",
        "clips",
        "cnn",
        "cod",
        "combat",
        "comedy",
        "comic",
        "comics",
        "commentary",
        "community",
        "computer",
        "consciousness",
        "conservative",
        "console",
        "conspiracy",
        "cosplay",
        "cover",
        "crafting",
        "crash",
        "creepy",
        "creepypasta",
        "crypto",
        "cryptocurrency",
        "culture",
        "cute",
        "daily vlog",
        "daily",
        "dance",
        "dantdm",
        "day",
        "dayz",
        "dc",
        "death",
        "democrat",
        "design",
        "destiny 2",
        "destiny",
        "discord",
        "disney",
        "diy",
        "dj",
        "dlc",
        "dog",
        "donald trump",
        "dope",
        "dota 2",
        "dota",
        "dragon",
        "drama",
        "drawing",
        "driving",
        "drone",
        "dubstep",
        "duty",
        "earth",
        "economics",
        "economy",
        "edit",
        "edm",
        "education",
        "eggs",
        "electronic",
        "england",
        "entertainment",
        "epic",
        "eth",
        "ethereum",
        "exploration",
        "extreme",
        "facebook",
        "fail",
        "fake news",
        "fallout 4",
        "family friendly",
        "family",
        "fantasy",
        "far cry 5",
        "fashion",
        "fiction",
        "film & animation",
        "film",
        "final fantasy",
        "final",
        "fire",
        "first look",
        "fitness",
        "flash",
        "flat earth",
        "food",
        "football",
        "fortnite",
        "fox news",
        "fox",
        "fps",
        "fpv",
        "free speech",
        "freedom",
        "freestyle",
        "full time rving",
        "fun",
        "funny moments",
        "funny",
        "future bass",
        "future",
        "galaxy",
        "game reviews",
        "game",
        "gameplay",
        "gamer",
        "gamers",
        "games",
        "gaming",
        "garden",
        "germany",
        "ghost",
        "god",
        "gold",
        "government",
        "grand theft auto",
        "gta v",
        "gta",
        "guitar",
        "gun",
        "guns",
        "guru",
        "hack",
        "halloween",
        "halo",
        "hangoutsonair",
        "happy",
        "hardcore",
        "health",
        "help",
        "hero",
        "hilarious",
        "hillary clinton",
        "hip hop",
        "hiphop",
        "history",
        "hoa",
        "holiday",
        "horror",
        "house",
        "how to",
        "how-to",
        "howto",
        "humor",
        "humour",
        "ico",
        "illuminati",
        "indie",
        "industry",
        "insane",
        "instrumental",
        "investing",
        "ios",
        "iphone",
        "island",
        "jesus",
        "juvenile fiction",
        "knife",
        "latest news",
        "lbrytvpaidbeta",
        "league of legends",
        "league",
        "learning",
        "lee",
        "lessons",
        "lets play",
        "lets",
        "level",
        "liberal",
        "libertarian",
        "liberty",
        "light",
        "linux",
        "litecoin",
        "lol",
        "loot",
        "lord",
        "love",
        "magic",
        "manga",
        "mario",
        "marvel",
        "mass effect",
        "master",
        "mature",
        "media",
        "meme",
        "memes",
        "metal",
        "microsoft",
        "military",
        "minecraft",
        "mining",
        "mix",
        "mmo",
        "mmorpg",
        "mobile",
        "mod",
        "modded",
        "mods",
        "mojang",
        "money",
        "motivation",
        "movie",
        "movies",
        "msnbc",
        "multiplayer",
        "music video",
        "music",
        "muslim",
        "mw2",
        "mw3",
        "nasa",
        "nature",
        "nbc",
        "new music",
        "news radio",
        "news",
        "ninja",
        "nintendo switch",
        "nintendo",
        "non-profits",
        "noob",
        "nvidia",
        "online learning",
        "online",
        "open world",
        "outdoor",
        "overwatch",
        "pacman",
        "paladins",
        "paranormal",
        "parody",
        "patreon",
        "paypal",
        "pc game",
        "pc gaming",
        "pc",
        "peace",
        "pets",
        "photography",
        "planet",
        "play",
        "player",
        "playing",
        "playlist",
        "plays",
        "playstation",
        "playthrough",
        "podcast",
        "poetry",
        "pokemon",
        "political",
        "politics",
        "pop culture",
        "pop",
        "portugal",
        "post",
        "prank",
        "press",
        "pro",
        "progressive talk",
        "progressive",
        "ps2",
        "ps3",
        "ps4",
        "pubg mobile",
        "pubg",
        "puzzle",
        "pvp",
        "quad",
        "quest",
        "race",
        "racing",
        "rainbow",
        "random",
        "rant",
        "rap",
        "raw",
        "rda",
        "react",
        "reaction",
        "reading",
        "reaper",
        "religion",
        "remix",
        "republican",
        "resident evil",
        "retro",
        "reviews",
        "ripple",
        "roblox",
        "rock",
        "role-playing game",
        "role-playing",
        "rpg",
        "rta",
        "rv park",
        "rv",
        "samsung",
        "sandbox",
        "satire",
        "school",
        "sci-fi",
        "science fiction",
        "science",
        "scotland",
        "season",
        "secret",
        "secular talk",
        "secular",
        "sega",
        "senate",
        "server",
        "sharefactory",
        "shooter game",
        "shooting",
        "silly",
        "sims 4",
        "sims",
        "simulation",
        "singing",
        "skyrim",
        "smok",
        "sniper",
        "sniping",
        "software",
        "solar",
        "song",
        "sony",
        "soul",
        "sound",
        "space",
        "special",
        "spirituality",
        "sports",
        "squad gameplay",
        "star wars",
        "star",
        "steam",
        "stories",
        "strategy",
        "stream",
        "studio",
        "stupid",
        "style",
        "subscribe",
        "super smash bros",
        "survival horror",
        "survival",
        "switch",
        "tactical",
        "teaser",
        "tech",
        "technology",
        "timelapse",
        "top 10",
        "tourism",
        "trading",
        "trailer",
        "training",
        "trap",
        "travel trailer",
        "travel",
        "trending",
        "truck",
        "trump",
        "truth",
        "tutorial",
        "twitch",
        "twitter",
        "ubisoft",
        "ufo",
        "unboxing",
        "united states",
        "universe",
        "vacation",
        "vape",
        "vaping",
        "vapor",
        "vegan",
        "video blog",
        "video game culture",
        "video game",
        "video games",
        "videogame",
        "videogames",
        "viral",
        "vlogging",
        "vr",
        "walkthrough",
        "war",
        "warrior",
        "water",
        "weapons",
        "weird",
        "wii u",
        "wii",
        "windows",
        "workout",
        "world of warcraft",
        "world",
        "wrestling",
        "ww2",
        "wwe",
        "xbox",
        "xbox360",
        "zombie",
        "zombies",
        "19th century",
        "4k",

        "español",
        "tecnología",
        "criptomonedas",
        "economía",
        "bitcoin",
        "educación",
        "videojuegos",
        "música",
        "noticias",
        "ciencia",
        "deportes",
        "latinoamérica",
        "latam",
        "conspiración",
        "humor",
        "política",
        "tutoriales",
    ]
}
