name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: macOS-latest
    env:
      MINT_PATH: ${{ github.workspace }}/mint
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mint
        run: brew install mint
      - name: Bootstrap mint dependencies
        run: mint bootstrap
      - name: SwiftFormat
        run: mint run swiftformat --lint --verbose .
